---
- name: Download package
  get_url:
    url: "https://github.com/jgraph/drawio-desktop/releases/download/v{{ drawio_version }}/draw.io-amd64-{{ drawio_version }}.deb"
    dest: "/tmp/drawio-{{ drawio_version }}.deb"

- name: Install package
  become: true
  apt:
    deb: "/tmp/drawio-{{ drawio_version }}.deb"
    update_cache: true
